/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.gform.recalculation

import uk.gov.hmrc.auth.core.{ ConfidenceLevel, Enrolments, User }
import uk.gov.hmrc.gform.auth.models.{ AuthenticatedRetrievals, GovernmentGatewayId, OtherRetrievals }
import uk.gov.hmrc.gform.sharedmodel.BooleanExprCache
import uk.gov.hmrc.gform.sharedmodel.formtemplate.{ DataSource, IdentifierName, ServiceName }
import uk.gov.hmrc.gform.sharedmodel.AffinityGroup
import uk.gov.hmrc.gform.sharedmodel.VariadicValue.{ Many, One }
import uk.gov.hmrc.gform.recalculation.EvaluationStatus._
import uk.gov.hmrc.gform.sharedmodel.form.ThirdPartyData

object FormModelOpticsTests4 extends DependencyGraphFixture {

  val data = List(
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amountA"    -> One("1"),
        "1_amountB"    -> One("10"),
        "2_addAnother" -> Many(List("1")),
        "2_amountA"    -> One("2"),
        "2_amountB"    -> One("20")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2"
      ),
      EvaluationContext.empty,
      AnswerMap(),
      List(
        "1 - A: £1.00, B: £10.00.",
        "<p>1 - A: £1.00, B: £10.00.</p>",
        "2 - A: £2.00, B: £20.00.",
        "<p>2 - A: £2.00, B: £20.00.</p>",
        "amountA: £1.00, £2.00",
        "amountB: £10.00, £20.00",
        "amountA + £12.00: £13.00, £14.00",
        "£12.00 + amountA: £13.00, £14.00",
        "amountA + amountB: £11.00, £22.00",
        "amountB + amountA: £11.00, £22.00",
        "amountA - £12.00: -£11.00, -£10.00",
        "£12.00 - amountA: £11.00, £10.00",
        "amountA - amountB: -£9.00, -£18.00",
        "amountB - amountA: £9.00, £18.00",
        "amountA * £12.00: £12.00, £24.00",
        "£12.00 * amountA: £12.00, £24.00",
        "amountA * amountB: £10.00, £40.00",
        "amountB * amountA: £10.00, £40.00",
        "amountA / £12.00: £0.08, £0.16",
        "£12.00 / amountA: £12.00, £6.00",
        "amountA / amountB: £0.10, £0.10",
        "amountB / amountA: £10.00, £10.00"
      ),
      "arithmetic-atl.json Generated"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_primary"    -> Many(List("foo")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_primary"    -> Many(List("bar")),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3"),
        "3_primary"    -> Many(List("foo")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_primary" -> OptionResult(List("foo")),
        "2_amount"  -> NumberResult(2),
        "2_primary" -> OptionResult(List("bar")),
        "3_amount"  -> NumberResult(3),
        "3_primary" -> OptionResult(List("foo")),
        "secret"    -> Empty
      ),
      List(
        "1 - data: 1 : Foo.",
        "<p>1 - data: 1 : Foo.</p>",
        "2 - data: 2 : Bar.",
        "<p>2 - data: 2 : Bar.</p>",
        "3 - data: 3 : Foo.",
        "<p>3 - data: 3 : Foo.</p>",
        "calculation.sum = 46",
        "calculation = 11, 22, 13",
        "offset = 10",
        "amount: 1, 2, 3",
        "primary: Foo, Bar, Foo",
        "primary contains 'foo': Yes"
      ),
      "sum-with-contains.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_primary"    -> Many(List("foo")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_primary"    -> Many(List("bar")),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4"),
        "3_primary"    -> Many(List("foo")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_primary" -> OptionResult(List("foo")),
        "2_amount"  -> NumberResult(2),
        "2_primary" -> OptionResult(List("bar")),
        "3_amount"  -> NumberResult(4),
        "3_primary" -> OptionResult(List("foo")),
        "secret"    -> Hidden
      ),
      List(
        "1 - data: 1 : Foo.",
        "<p>1 - data: 1 : Foo.</p>",
        "2 - data: 2 : Bar.",
        "<p>2 - data: 2 : Bar.</p>",
        "3 - data: 4 : Foo.",
        "<p>3 - data: 4 : Foo.</p>",
        "calculation.sum = 47",
        "calculation = 11, 22, 14",
        "offset = 10",
        "amount: 1, 2, 4",
        "primary: Foo, Bar, Foo",
        "primary contains 'foo': Yes"
      ),
      "sum-with-contains.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3"
      ),
      EvaluationContext.empty.copy(
        retrievals = AuthenticatedRetrievals(
          GovernmentGatewayId(""),
          Enrolments(Set.empty),
          AffinityGroup.Individual,
          "group-id",
          None,
          OtherRetrievals.empty,
          ConfidenceLevel.L50,
          Some(User)
        )
      ),
      AnswerMap(
        "1_amount" -> NumberResult(1),
        "2_amount" -> NumberResult(2),
        "3_amount" -> NumberResult(3),
        "secret"   -> Empty
      ),
      List(
        "1 - data: 1.",
        "<p>1 - data: 1.</p>",
        "2 - data: 2.",
        "<p>2 - data: 2.</p>",
        "3 - data: 3.",
        "<p>3 - data: 3.</p>",
        "calculation.sum = 36",
        "calculation = 11, 12, 13",
        "amount: 1, 2, 3",
        "auth.ggLogin: Yes"
      ),
      "sum-with-auth-login.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3"
      ),
      EvaluationContext.empty.copy(
        retrievals = AuthenticatedRetrievals(
          GovernmentGatewayId(""),
          Enrolments(Set.empty),
          AffinityGroup.Individual,
          "group-id",
          None,
          OtherRetrievals.empty,
          ConfidenceLevel.L50,
          Some(User)
        )
      ),
      AnswerMap(
        "1_amount" -> NumberResult(1),
        "2_amount" -> NumberResult(2),
        "3_amount" -> NumberResult(4),
        "secret"   -> Hidden
      ),
      List(
        "1 - data: 1.",
        "<p>1 - data: 1.</p>",
        "2 - data: 2.",
        "<p>2 - data: 2.</p>",
        "3 - data: 4.",
        "<p>3 - data: 4.</p>",
        "calculation.sum = 37",
        "calculation = 11, 12, 14",
        "amount: 1, 2, 4",
        "auth.ggLogin: Yes"
      ),
      "sum-with-auth-login.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_showVat"    -> Many(List("yes")),
        "1_vatNumber"  -> One("77777777"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_showVat"    -> Many(List("yes")),
        "2_vatNumber"  -> One("99999999"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3"),
        "3_showVat"    -> Many(List("no")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty.copy(
        thirdPartyData = ThirdPartyData.empty.copy(
          booleanExprCache = BooleanExprCache(
            Map(
              DataSource.Enrolment(ServiceName("HMCE-VATDEC-ORG"), IdentifierName("VatRegNo")) -> Map(
                "77777777" -> true
              )
            )
          )
        )
      ),
      AnswerMap(
        "1_amount"    -> NumberResult(1),
        "1_showVat"   -> OptionResult(List("yes")),
        "1_vatNumber" -> StringResult("77777777"),
        "2_amount"    -> NumberResult(2),
        "2_showVat"   -> OptionResult(List("yes")),
        "2_vatNumber" -> StringResult("99999999"),
        "3_amount"    -> NumberResult(3),
        "3_showVat"   -> OptionResult(List("no")),
        "3_vatNumber" -> Hidden,
        "secret"      -> Empty
      ),
      List(
        "1 - data: 1 : 77777777.",
        "<p>1 - data: 1 : 77777777.</p>",
        "2 - data: 2 : 99999999.",
        "<p>2 - data: 2 : 99999999.</p>",
        "3 - data: 3 : .",
        "<p>3 - data: 3 : .</p>",
        "calculation.sum = 56",
        "calculation = 11, 22, 23",
        "amount: 1, 2, 3",
        "vatNumber: 77777777, 99999999",
        "vatNumber in user.enrolments.HMCE-VATDEC-ORG.VatRegNo: Yes, No, No"
      ),
      "sum-with-in.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_showVat"    -> Many(List("yes")),
        "1_vatNumber"  -> One("77777777"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_showVat"    -> Many(List("yes")),
        "2_vatNumber"  -> One("99999999"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4"),
        "3_showVat"    -> Many(List("no")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty.copy(
        thirdPartyData = ThirdPartyData.empty.copy(
          booleanExprCache = BooleanExprCache(
            Map(
              DataSource.Enrolment(ServiceName("HMCE-VATDEC-ORG"), IdentifierName("VatRegNo")) -> Map(
                "77777777" -> true
              )
            )
          )
        )
      ),
      AnswerMap(
        "1_amount"    -> NumberResult(1),
        "1_showVat"   -> OptionResult(List("yes")),
        "1_vatNumber" -> StringResult("77777777"),
        "2_amount"    -> NumberResult(2),
        "2_showVat"   -> OptionResult(List("yes")),
        "2_vatNumber" -> StringResult("99999999"),
        "3_amount"    -> NumberResult(4),
        "3_showVat"   -> OptionResult(List("no")),
        "3_vatNumber" -> Hidden,
        "secret"      -> Hidden
      ),
      List(
        "1 - data: 1 : 77777777.",
        "<p>1 - data: 1 : 77777777.</p>",
        "2 - data: 2 : 99999999.",
        "<p>2 - data: 2 : 99999999.</p>",
        "3 - data: 4 : .",
        "<p>3 - data: 4 : .</p>",
        "calculation.sum = 57",
        "calculation = 11, 22, 24",
        "amount: 1, 2, 4",
        "vatNumber: 77777777, 99999999",
        "vatNumber in user.enrolments.HMCE-VATDEC-ORG.VatRegNo: Yes, No, No"
      ),
      "sum-with-in.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother"  -> Many(List("0")),
        "1_amount"      -> One("1"),
        "1_country"     -> One("Canada"),
        "1_showCountry" -> Many(List("yes")),
        "2_addAnother"  -> Many(List("0")),
        "2_amount"      -> One("2"),
        "2_showCountry" -> Many(List("no")),
        "3_addAnother"  -> Many(List("1")),
        "3_amount"      -> One("3"),
        "3_country"     -> One("France"),
        "3_showCountry" -> Many(List("yes")),
        "dummy"         -> One("dummy"),
        "homeCountry"   -> One("France")
      ),
      List(
        "n0",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ar1.2",
        "ap1.3.0",
        "ap1.3.1",
        "ar1.3",
        "n2"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"      -> NumberResult(1),
        "1_country"     -> StringResult("Canada"),
        "1_showCountry" -> OptionResult(List("yes")),
        "2_amount"      -> NumberResult(2),
        "2_country"     -> Hidden,
        "2_showCountry" -> OptionResult(List("no")),
        "3_amount"      -> NumberResult(3),
        "3_country"     -> StringResult("France"),
        "3_showCountry" -> OptionResult(List("yes")),
        "homeCountry"   -> StringResult("France"),
        "secret"        -> Empty
      ),
      List(
        "1 - data: 1 : Canada : 21 : 21.",
        "<p>1 - data: 1 : Canada : 21 : 21.</p>",
        "2 - data: 2 :  : 22 : 43.",
        "<p>2 - data: 2 : : 22 : 43.</p>",
        "3 - data: 3 : France : 13 : 56.",
        "<p>3 - data: 3 : France : 13 : 56.</p>",
        "calculation.sum = 56",
        "calculation = 21, 22, 13",
        "homeCountry: France",
        "amount: 1, 2, 3",
        "country: Canada, France",
        "homeCountry in country: Yes"
      ),
      "sum-with-has-answer.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother"  -> Many(List("0")),
        "1_amount"      -> One("1"),
        "1_country"     -> One("Canada"),
        "1_showCountry" -> Many(List("yes")),
        "2_addAnother"  -> Many(List("0")),
        "2_amount"      -> One("2"),
        "2_showCountry" -> Many(List("no")),
        "3_addAnother"  -> Many(List("1")),
        "3_amount"      -> One("4"),
        "3_country"     -> One("France"),
        "3_showCountry" -> Many(List("yes")),
        "dummy"         -> One("dummy"),
        "homeCountry"   -> One("France")
      ),
      List(
        "n0",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ar1.2",
        "ap1.3.0",
        "ap1.3.1",
        "ar1.3",
        "n2"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"      -> NumberResult(1),
        "1_country"     -> StringResult("Canada"),
        "1_showCountry" -> OptionResult(List("yes")),
        "2_amount"      -> NumberResult(2),
        "2_country"     -> Hidden,
        "2_showCountry" -> OptionResult(List("no")),
        "3_amount"      -> NumberResult(4),
        "3_country"     -> StringResult("France"),
        "3_showCountry" -> OptionResult(List("yes")),
        "homeCountry"   -> StringResult("France"),
        "secret"        -> Hidden
      ),
      List(
        "1 - data: 1 : Canada : 21 : 21.",
        "<p>1 - data: 1 : Canada : 21 : 21.</p>",
        "2 - data: 2 :  : 22 : 43.",
        "<p>2 - data: 2 : : 22 : 43.</p>",
        "3 - data: 4 : France : 14 : 57.",
        "<p>3 - data: 4 : France : 14 : 57.</p>",
        "calculation.sum = 57",
        "calculation = 21, 22, 14",
        "homeCountry: France",
        "amount: 1, 2, 4",
        "country: Canada, France",
        "homeCountry in country: Yes"
      ),
      "sum-with-has-answer.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_addAnother" -> OptionResult(List("0")),
        "1_amount"     -> NumberResult(1),
        "2_addAnother" -> OptionResult(List("0")),
        "2_amount"     -> NumberResult(2),
        "3_addAnother" -> OptionResult(List("1")),
        "3_amount"     -> NumberResult(3),
        "secret"       -> Empty
      ),
      List(
        "1 - data: 1.",
        "<p>1 - data: 1.</p>",
        "2 - data: 2.",
        "<p>2 - data: 2.</p>",
        "3 - data: 3.",
        "<p>3 - data: 3.</p>",
        "calculation.sum = 56",
        "calculation = 11, 22, 23",
        "amount: 1, 2, 3",
        "addAnother.first: Yes, No, No"
      ),
      "sum-with-first.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_addAnother" -> OptionResult(List("0")),
        "1_amount"     -> NumberResult(1),
        "2_addAnother" -> OptionResult(List("0")),
        "2_amount"     -> NumberResult(2),
        "3_addAnother" -> OptionResult(List("1")),
        "3_amount"     -> NumberResult(4),
        "secret"       -> Hidden
      ),
      List(
        "1 - data: 1.",
        "<p>1 - data: 1.</p>",
        "2 - data: 2.",
        "<p>2 - data: 2.</p>",
        "3 - data: 4.",
        "<p>3 - data: 4.</p>",
        "calculation.sum = 57",
        "calculation = 11, 22, 24",
        "amount: 1, 2, 4",
        "addAnother.first: Yes, No, No"
      ),
      "sum-with-first.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_adjust"     -> Many(List("yes")),
        "1_amount"     -> One("1"),
        "1_partA"      -> One("FOO"),
        "1_partB"      -> One("BAR"),
        "2_addAnother" -> Many(List("0")),
        "2_adjust"     -> Many(List("yes")),
        "2_amount"     -> One("2"),
        "2_partA"      -> One("FOO"),
        "2_partB"      -> One("BAR"),
        "3_addAnother" -> Many(List("1")),
        "3_adjust"     -> Many(List("no")),
        "3_amount"     -> One("3"),
        "3_partA"      -> One("FOO"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_adjust" -> OptionResult(List("yes")),
        "1_amount" -> NumberResult(1),
        "1_partA"  -> StringResult("FOO"),
        "1_partB"  -> StringResult("BAR"),
        "2_adjust" -> OptionResult(List("yes")),
        "2_amount" -> NumberResult(2),
        "2_partA"  -> StringResult("FOO"),
        "2_partB"  -> StringResult("BAR"),
        "3_adjust" -> OptionResult(List("no")),
        "3_amount" -> NumberResult(3),
        "3_partA"  -> StringResult("FOO"),
        "3_partB"  -> Hidden,
        "secret"   -> Hidden
      ),
      List(
        "1 - data: 1 : FOO : BAR.",
        "<p>1 - data: 1 : FOO : BAR.</p>",
        "2 - data: 2 : FOO : BAR.",
        "<p>2 - data: 2 : FOO : BAR.</p>",
        "3 - data: 3 : FOO : .",
        "<p>3 - data: 3 : FOO : .</p>",
        "calculation.sum = 36",
        "calculationSwapped.sum = 36",
        "calculation = 11, 12, 13",
        "calculationSwapped = 11, 12, 13",
        "amount: 1, 2, 3",
        "partA: FOO, FOO, FOO",
        "partB: BAR, BAR",
        "duplicateExists(partA, partB): Yes"
      ),
      "sum-with-duplicate-exists.json duplicate exists and secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_adjust"     -> Many(List("yes")),
        "1_amount"     -> One("1"),
        "1_partA"      -> One("BAZ"),
        "1_partB"      -> One("BAR"),
        "2_addAnother" -> Many(List("0")),
        "2_adjust"     -> Many(List("yes")),
        "2_amount"     -> One("2"),
        "2_partA"      -> One("BAR"),
        "2_partB"      -> One("FOO"),
        "3_addAnother" -> Many(List("1")),
        "3_adjust"     -> Many(List("yes")),
        "3_amount"     -> One("3"),
        "3_partA"      -> One("BAZ"),
        "3_partB"      -> One("FOO"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_adjust" -> OptionResult(List("yes")),
        "1_amount" -> NumberResult(1),
        "1_partA"  -> StringResult("BAZ"),
        "1_partB"  -> StringResult("BAR"),
        "2_adjust" -> OptionResult(List("yes")),
        "2_amount" -> NumberResult(2),
        "2_partA"  -> StringResult("BAR"),
        "2_partB"  -> StringResult("FOO"),
        "3_adjust" -> OptionResult(List("yes")),
        "3_amount" -> NumberResult(3),
        "3_partA"  -> StringResult("BAZ"),
        "3_partB"  -> StringResult("FOO"),
        "secret"   -> Empty
      ),
      List(
        "1 - data: 1 : BAZ : BAR.",
        "<p>1 - data: 1 : BAZ : BAR.</p>",
        "2 - data: 2 : BAR : FOO.",
        "<p>2 - data: 2 : BAR : FOO.</p>",
        "3 - data: 3 : BAZ : FOO.",
        "<p>3 - data: 3 : BAZ : FOO.</p>",
        "calculation.sum = 66",
        "calculationSwapped.sum = 66",
        "calculation = 21, 22, 23",
        "calculationSwapped = 21, 22, 23",
        "amount: 1, 2, 3",
        "partA: BAZ, BAR, BAZ",
        "partB: BAR, FOO, FOO",
        "duplicateExists(partA, partB): No"
      ),
      "sum-with-duplicate-exists.json duplicate do not exists and secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_adjust"     -> Many(List("yes")),
        "1_amount"     -> One("1"),
        "1_brand"      -> One("FOO"),
        "2_addAnother" -> Many(List("0")),
        "2_adjust"     -> Many(List("no")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("0")),
        "3_adjust"     -> Many(List("yes")),
        "3_amount"     -> One("3"),
        "3_brand"      -> One("BAR"),
        "4_addAnother" -> Many(List("1")),
        "4_adjust"     -> Many(List("yes")),
        "4_amount"     -> One("4"),
        "4_brand"      -> One("BAZ"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ap0.4.1",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_adjust" -> OptionResult(List("yes")),
        "1_amount" -> NumberResult(1),
        "1_brand"  -> StringResult("FOO"),
        "2_adjust" -> OptionResult(List("no")),
        "2_amount" -> NumberResult(2),
        "2_brand"  -> Hidden,
        "3_adjust" -> OptionResult(List("yes")),
        "3_amount" -> NumberResult(3),
        "3_brand"  -> StringResult("BAR"),
        "4_adjust" -> OptionResult(List("yes")),
        "4_amount" -> NumberResult(4),
        "4_brand"  -> StringResult("BAZ"),
        "secret"   -> Empty
      ),
      List(
        "1 - data: 1 : FOO.",
        "<p>1 - data: 1 : FOO.</p>",
        "2 - data: 2 : .",
        "<p>2 - data: 2 : .</p>",
        "3 - data: 3 : BAR.",
        "<p>3 - data: 3 : BAR.</p>",
        "4 - data: 4 : BAZ.",
        "<p>4 - data: 4 : BAZ.</p>",
        "calculation.sum = 70",
        "calculation = 11, 22, 13, 24",
        "amount: 1, 2, 3, 4",
        "brand: FOO, BAR, BAZ",
        "brand match 'FOO|BAR': Yes, No, Yes, No"
      ),
      "sum-with-regex.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_adjust"     -> Many(List("yes")),
        "1_amount"     -> One("1"),
        "1_brand"      -> One("FOO"),
        "2_addAnother" -> Many(List("0")),
        "2_adjust"     -> Many(List("no")),
        "2_amount"     -> One("2"),
        "3_addAnother" -> Many(List("0")),
        "3_adjust"     -> Many(List("yes")),
        "3_amount"     -> One("3"),
        "3_brand"      -> One("BAR"),
        "4_addAnother" -> Many(List("1")),
        "4_adjust"     -> Many(List("yes")),
        "4_amount"     -> One("5"),
        "4_brand"      -> One("BAZ"),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ap0.4.1",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_adjust" -> OptionResult(List("yes")),
        "1_amount" -> NumberResult(1),
        "1_brand"  -> StringResult("FOO"),
        "2_adjust" -> OptionResult(List("no")),
        "2_amount" -> NumberResult(2),
        "2_brand"  -> Hidden,
        "3_adjust" -> OptionResult(List("yes")),
        "3_amount" -> NumberResult(3),
        "3_brand"  -> StringResult("BAR"),
        "4_adjust" -> OptionResult(List("yes")),
        "4_amount" -> NumberResult(5),
        "4_brand"  -> StringResult("BAZ"),
        "secret"   -> Hidden
      ),
      List(
        "1 - data: 1 : FOO.",
        "<p>1 - data: 1 : FOO.</p>",
        "2 - data: 2 : .",
        "<p>2 - data: 2 : .</p>",
        "3 - data: 3 : BAR.",
        "<p>3 - data: 3 : BAR.</p>",
        "4 - data: 5 : BAZ.",
        "<p>4 - data: 5 : BAZ.</p>",
        "calculation.sum = 71",
        "calculation = 11, 22, 13, 25",
        "amount: 1, 2, 3, 5",
        "brand: FOO, BAR, BAZ",
        "brand match 'FOO|BAR': Yes, No, Yes, No"
      ),
      "sum-with-regex.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_offset"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_offset"     -> One("123"),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("offset")),
        "3_offset"     -> One("100"),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("4"),
        "4_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_control" -> OptionResult(List("offset")),
        "1_offset"  -> NumberResult(1),
        "2_amount"  -> NumberResult(2),
        "2_control" -> OptionResult(List("offset")),
        "2_offset"  -> NumberResult(123),
        "3_amount"  -> NumberResult(3),
        "3_control" -> OptionResult(List("offset")),
        "3_offset"  -> NumberResult(100),
        "4_amount"  -> NumberResult(4),
        "4_control" -> OptionResult(List("keep")),
        "4_offset"  -> Hidden,
        "secret"    -> Empty
      ),
      List(
        "1 - data: 1 : 1.",
        "<p>1 - data: 1 : 1.</p>",
        "2 - data: 2 : 123.",
        "<p>2 - data: 2 : 123.</p>",
        "3 - data: 3 : 100.",
        "<p>3 - data: 3 : 100.</p>",
        "4 - data: 4 : 0.",
        "<p>4 - data: 4 : 0.</p>",
        "calculationGreaterThan.sum = 80",
        "calculationGreaterThan = 21, 12, 23, 24",
        "calculationGreaterThanOrEquals.sum = 70",
        "calculationGreaterThanOrEquals = 21, 12, 13, 24",
        "calculationLessThan.sum = 80",
        "calculationLessThan = 11, 22, 23, 24",
        "calculationLessThanOrEquals.sum = 70",
        "calculationLessThanOrEquals = 11, 22, 13, 24",
        "offsetGreaterThan = 20, 10, 20, 20",
        "offsetGreaterThanOrEquals = 20, 10, 10, 20",
        "offsetLessThan = 10, 20, 20, 20",
        "offsetLessThanOrEquals = 10, 20, 10, 20",
        "amount: 1, 2, 3, 4",
        "offset: 1, 123, 100, 0",
        "offset > 100: No, Yes, No, No",
        "offset >= 100: No, Yes, Yes, No",
        "offset < 100: Yes, No, No, No",
        "offset <= 100: Yes, No, Yes, No"
      ),
      "sum-with-greater-than-less-than.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_offset"     -> One("1"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_offset"     -> One("123"),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("offset")),
        "3_offset"     -> One("100"),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("5"),
        "4_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_control" -> OptionResult(List("offset")),
        "1_offset"  -> NumberResult(1),
        "2_amount"  -> NumberResult(2),
        "2_control" -> OptionResult(List("offset")),
        "2_offset"  -> NumberResult(123),
        "3_amount"  -> NumberResult(3),
        "3_control" -> OptionResult(List("offset")),
        "3_offset"  -> NumberResult(100),
        "4_amount"  -> NumberResult(5),
        "4_control" -> OptionResult(List("keep")),
        "4_offset"  -> Hidden,
        "secret"    -> Hidden
      ),
      List(
        "1 - data: 1 : 1.",
        "<p>1 - data: 1 : 1.</p>",
        "2 - data: 2 : 123.",
        "<p>2 - data: 2 : 123.</p>",
        "3 - data: 3 : 100.",
        "<p>3 - data: 3 : 100.</p>",
        "4 - data: 5 : 0.",
        "<p>4 - data: 5 : 0.</p>",
        "calculationGreaterThan.sum = 81",
        "calculationGreaterThan = 21, 12, 23, 25",
        "calculationGreaterThanOrEquals.sum = 71",
        "calculationGreaterThanOrEquals = 21, 12, 13, 25",
        "calculationLessThan.sum = 81",
        "calculationLessThan = 11, 22, 23, 25",
        "calculationLessThanOrEquals.sum = 71",
        "calculationLessThanOrEquals = 11, 22, 13, 25",
        "offsetGreaterThan = 20, 10, 20, 20",
        "offsetGreaterThanOrEquals = 20, 10, 10, 20",
        "offsetLessThan = 10, 20, 20, 20",
        "offsetLessThanOrEquals = 10, 20, 10, 20",
        "amount: 1, 2, 3, 5",
        "offset: 1, 123, 100, 0",
        "offset > 100: No, Yes, No, No",
        "offset >= 100: No, Yes, Yes, No",
        "offset < 100: Yes, No, No, No",
        "offset <= 100: Yes, No, Yes, No"
      ),
      "sum-with-greater-than-less-than.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_primary"    -> Many(List("foo")),
        "1_secondary"  -> Many(List("foo")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_primary"    -> Many(List("foo")),
        "2_secondary"  -> Many(List("bar")),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_primary"    -> Many(List("bar")),
        "3_secondary"  -> Many(List("foo")),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("4"),
        "4_primary"    -> Many(List("bar")),
        "4_secondary"  -> Many(List("bar")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"    -> NumberResult(1),
        "1_primary"   -> OptionResult(List("foo")),
        "1_secondary" -> OptionResult(List("foo")),
        "2_amount"    -> NumberResult(2),
        "2_primary"   -> OptionResult(List("foo")),
        "2_secondary" -> OptionResult(List("bar")),
        "3_amount"    -> NumberResult(3),
        "3_primary"   -> OptionResult(List("bar")),
        "3_secondary" -> OptionResult(List("foo")),
        "4_amount"    -> NumberResult(4),
        "4_primary"   -> OptionResult(List("bar")),
        "4_secondary" -> OptionResult(List("bar")),
        "secret"      -> Empty
      ),
      List(
        "1 - data: 1 : Foo : Foo.",
        "<p>1 - data: 1 : Foo : Foo.</p>",
        "2 - data: 2 : Foo : Bar.",
        "<p>2 - data: 2 : Foo : Bar.</p>",
        "3 - data: 3 : Bar : Foo.",
        "<p>3 - data: 3 : Bar : Foo.</p>",
        "4 - data: 4 : Bar : Bar.",
        "<p>4 - data: 4 : Bar : Bar.</p>",
        "calculation.sum = 70",
        "calculation = 11, 22, 23, 14",
        "offset = 10, 20, 20, 10",
        "amount: 1, 2, 3, 4",
        "primary: Foo, Foo, Bar, Bar",
        "secondary: Foo, Bar, Foo, Bar",
        "primary = secondary: Yes, No, No, Yes"
      ),
      "sum-with-equals-options.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_primary"    -> Many(List("foo")),
        "1_secondary"  -> Many(List("foo")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_primary"    -> Many(List("foo")),
        "2_secondary"  -> Many(List("bar")),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_primary"    -> Many(List("bar")),
        "3_secondary"  -> Many(List("foo")),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("5"),
        "4_primary"    -> Many(List("bar")),
        "4_secondary"  -> Many(List("bar")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"    -> NumberResult(1),
        "1_primary"   -> OptionResult(List("foo")),
        "1_secondary" -> OptionResult(List("foo")),
        "2_amount"    -> NumberResult(2),
        "2_primary"   -> OptionResult(List("foo")),
        "2_secondary" -> OptionResult(List("bar")),
        "3_amount"    -> NumberResult(3),
        "3_primary"   -> OptionResult(List("bar")),
        "3_secondary" -> OptionResult(List("foo")),
        "4_amount"    -> NumberResult(5),
        "4_primary"   -> OptionResult(List("bar")),
        "4_secondary" -> OptionResult(List("bar")),
        "secret"      -> Hidden
      ),
      List(
        "1 - data: 1 : Foo : Foo.",
        "<p>1 - data: 1 : Foo : Foo.</p>",
        "2 - data: 2 : Foo : Bar.",
        "<p>2 - data: 2 : Foo : Bar.</p>",
        "3 - data: 3 : Bar : Foo.",
        "<p>3 - data: 3 : Bar : Foo.</p>",
        "4 - data: 5 : Bar : Bar.",
        "<p>4 - data: 5 : Bar : Bar.</p>",
        "calculation.sum = 71",
        "calculation = 11, 22, 23, 15",
        "offset = 10, 20, 20, 10",
        "amount: 1, 2, 3, 5",
        "primary: Foo, Foo, Bar, Bar",
        "secondary: Foo, Bar, Foo, Bar",
        "primary = secondary: Yes, No, No, Yes"
      ),
      "sum-with-equals-options.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_number"     -> One("1"),
        "1_string"     -> One("FOO"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_number"     -> One("2"),
        "2_string"     -> One("BAR"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_control" -> OptionResult(List("offset")),
        "1_number"  -> NumberResult(1),
        "1_string"  -> StringResult("FOO"),
        "2_amount"  -> NumberResult(2),
        "2_control" -> OptionResult(List("offset")),
        "2_number"  -> NumberResult(2),
        "2_string"  -> StringResult("BAR"),
        "3_amount"  -> NumberResult(3),
        "3_control" -> OptionResult(List("keep")),
        "3_number"  -> Hidden,
        "3_string"  -> Hidden,
        "secret"    -> Empty
      ),
      List(
        "1 - data: 1 : 1 : FOO.",
        "<p>1 - data: 1 : 1 : FOO.</p>",
        "2 - data: 2 : 2 : BAR.",
        "<p>2 - data: 2 : 2 : BAR.</p>",
        "3 - data: 3 : 0 : .",
        "<p>3 - data: 3 : 0 : .</p>",
        "calculationSetLiteralNumber.sum = 56",
        "calculationLiteralSetNumber.sum = 56",
        "calculationSetLiteralString.sum = 56",
        "calculationLiteralSetString.sum = 56",
        "calculationSetLiteralNumber = 11, 22, 23",
        "calculationLiteralSetNumber = 11, 22, 23",
        "calculationSetLiteralString = 11, 22, 23",
        "calculationLiteralSetString = 11, 22, 23",
        "setLiteralNumber = 10, 20, 20",
        "literalSetNumber = 10, 20, 20",
        "setLiteralString = 10, 20, 20",
        "literalSetString = 10, 20, 20",
        "amount: 1, 2, 3",
        "number: 1, 2, 0"
      ),
      "sum-with-equals-set-and-literal.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_number"     -> One("1"),
        "1_string"     -> One("FOO"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_number"     -> One("2"),
        "2_string"     -> One("BAR"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4"),
        "3_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"  -> NumberResult(1),
        "1_control" -> OptionResult(List("offset")),
        "1_number"  -> NumberResult(1),
        "1_string"  -> StringResult("FOO"),
        "2_amount"  -> NumberResult(2),
        "2_control" -> OptionResult(List("offset")),
        "2_number"  -> NumberResult(2),
        "2_string"  -> StringResult("BAR"),
        "3_amount"  -> NumberResult(4),
        "3_control" -> OptionResult(List("keep")),
        "3_number"  -> Hidden,
        "3_string"  -> Hidden,
        "secret"    -> Hidden
      ),
      List(
        "1 - data: 1 : 1 : FOO.",
        "<p>1 - data: 1 : 1 : FOO.</p>",
        "2 - data: 2 : 2 : BAR.",
        "<p>2 - data: 2 : 2 : BAR.</p>",
        "3 - data: 4 : 0 : .",
        "<p>3 - data: 4 : 0 : .</p>",
        "calculationSetLiteralNumber.sum = 57",
        "calculationLiteralSetNumber.sum = 57",
        "calculationSetLiteralString.sum = 57",
        "calculationLiteralSetString.sum = 57",
        "calculationSetLiteralNumber = 11, 22, 24",
        "calculationLiteralSetNumber = 11, 22, 24",
        "calculationSetLiteralString = 11, 22, 24",
        "calculationLiteralSetString = 11, 22, 24",
        "setLiteralNumber = 10, 20, 20",
        "literalSetNumber = 10, 20, 20",
        "setLiteralString = 10, 20, 20",
        "literalSetString = 10, 20, 20",
        "amount: 1, 2, 4",
        "number: 1, 2, 0"
      ),
      "sum-with-equals-set-and-literal.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnotherA" -> Many(List("1")),
        "1_addAnotherB" -> Many(List("0")),
        "1_amountA"     -> One("1"),
        "1_amountB"     -> One("2"),
        "1_controlA"    -> Many(List("offset")),
        "1_controlB"    -> Many(List("offset")),
        "1_dateA-day"   -> One("1"),
        "1_dateA-month" -> One("1"),
        "1_dateA-year"  -> One("2025"),
        "1_dateB-day"   -> One("2"),
        "1_dateB-month" -> One("2"),
        "1_dateB-year"  -> One("2024"),
        "2_addAnotherB" -> Many(List("0")),
        "2_amountB"     -> One("3"),
        "2_controlB"    -> Many(List("offset")),
        "2_dateB-day"   -> One("3"),
        "2_dateB-month" -> One("3"),
        "2_dateB-year"  -> One("2023"),
        "3_addAnotherB" -> Many(List("1")),
        "3_amountB"     -> One("4"),
        "3_controlB"    -> Many(List("keep"))
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ap1.2.1",
        "ar1.2",
        "ap1.3.0",
        "ar1.3"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amountA"     -> NumberResult(1),
        "1_amountB"     -> NumberResult(2),
        "1_controlA"    -> OptionResult(List("offset")),
        "1_controlB"    -> OptionResult(List("offset")),
        "1_dateA-day"   -> NumberResult(1),
        "1_dateA-month" -> NumberResult(1),
        "1_dateA-year"  -> NumberResult(2025),
        "1_dateB-day"   -> NumberResult(2),
        "1_dateB-month" -> NumberResult(2),
        "1_dateB-year"  -> NumberResult(2024),
        "2_amountB"     -> NumberResult(3),
        "2_controlB"    -> OptionResult(List("offset")),
        "2_dateB-day"   -> NumberResult(3),
        "2_dateB-month" -> NumberResult(3),
        "2_dateB-year"  -> NumberResult(2023),
        "3_amountB"     -> NumberResult(4),
        "3_controlB"    -> OptionResult(List("keep")),
        "3_dateB-day"   -> Hidden,
        "3_dateB-month" -> Hidden,
        "3_dateB-year"  -> Hidden,
        "secret"        -> Empty
      ),
      List(
        "1 - data: 1 : 1 January 2025",
        "<p>1 - data: 1 : 1 January 2025</p>",
        "1 - data: 2 : 2 February 2024",
        "<p>1 - data: 2 : 2 February 2024</p>",
        "2 - data: 3 : 3 March 2023",
        "<p>2 - data: 3 : 3 March 2023</p>",
        "3 - data: 4 : ",
        "<p>3 - data: 4 :</p>",
        "calculation.sum = 50",
        "calculation = 13, 13, 24",
        "amountA: 1",
        "amountB: 2, 3, 4",
        "dateA: 1 January 2025",
        "dateB: 2 February 2024, 3 March 2023",
        "dateA after 31122024: Yes",
        "dateB before 01012024: No, Yes, No",
        "dateA after 31122024 || dateB before 01012024: Yes, Yes, No",
        "offset: 10, 10, 20"
      ),
      "sum-with-or-and-two-atls.json Yes x No and secret found"
    ),
    (
      MongoUserData(
        "1_addAnotherA" -> Many(List("1")),
        "1_addAnotherB" -> Many(List("0")),
        "1_amountA"     -> One("1"),
        "1_amountB"     -> One("2"),
        "1_controlA"    -> Many(List("offset")),
        "1_controlB"    -> Many(List("offset")),
        "1_dateA-day"   -> One("1"),
        "1_dateA-month" -> One("1"),
        "1_dateA-year"  -> One("2025"),
        "1_dateB-day"   -> One("2"),
        "1_dateB-month" -> One("2"),
        "1_dateB-year"  -> One("2024"),
        "2_addAnotherB" -> Many(List("0")),
        "2_amountB"     -> One("3"),
        "2_controlB"    -> Many(List("offset")),
        "2_dateB-day"   -> One("3"),
        "2_dateB-month" -> One("3"),
        "2_dateB-year"  -> One("2023"),
        "3_addAnotherB" -> Many(List("1")),
        "3_amountB"     -> One("5"),
        "3_controlB"    -> Many(List("keep"))
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ap1.2.1",
        "ar1.2",
        "ap1.3.0",
        "ar1.3"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amountA"     -> NumberResult(1),
        "1_amountB"     -> NumberResult(2),
        "1_controlA"    -> OptionResult(List("offset")),
        "1_controlB"    -> OptionResult(List("offset")),
        "1_dateA-day"   -> NumberResult(1),
        "1_dateA-month" -> NumberResult(1),
        "1_dateA-year"  -> NumberResult(2025),
        "1_dateB-day"   -> NumberResult(2),
        "1_dateB-month" -> NumberResult(2),
        "1_dateB-year"  -> NumberResult(2024),
        "2_amountB"     -> NumberResult(3),
        "2_controlB"    -> OptionResult(List("offset")),
        "2_dateB-day"   -> NumberResult(3),
        "2_dateB-month" -> NumberResult(3),
        "2_dateB-year"  -> NumberResult(2023),
        "3_amountB"     -> NumberResult(5),
        "3_controlB"    -> OptionResult(List("keep")),
        "3_dateB-day"   -> Hidden,
        "3_dateB-month" -> Hidden,
        "3_dateB-year"  -> Hidden,
        "secret"        -> Hidden
      ),
      List(
        "1 - data: 1 : 1 January 2025",
        "<p>1 - data: 1 : 1 January 2025</p>",
        "1 - data: 2 : 2 February 2024",
        "<p>1 - data: 2 : 2 February 2024</p>",
        "2 - data: 3 : 3 March 2023",
        "<p>2 - data: 3 : 3 March 2023</p>",
        "3 - data: 5 : ",
        "<p>3 - data: 5 :</p>",
        "calculation.sum = 51",
        "calculation = 13, 13, 25",
        "amountA: 1",
        "amountB: 2, 3, 5",
        "dateA: 1 January 2025",
        "dateB: 2 February 2024, 3 March 2023",
        "dateA after 31122024: Yes",
        "dateB before 01012024: No, Yes, No",
        "dateA after 31122024 || dateB before 01012024: Yes, Yes, No",
        "offset: 10, 10, 20"
      ),
      "sum-with-or-and-two-atls.json Yes x No and secret not found"
    ),
    (
      MongoUserData(
        "1_addAnotherA" -> Many(List("1")),
        "1_addAnotherB" -> Many(List("0")),
        "1_amountA"     -> One("1"),
        "1_amountB"     -> One("2"),
        "1_controlA"    -> Many(List("offset")),
        "1_controlB"    -> Many(List("offset")),
        "1_dateA-day"   -> One("1"),
        "1_dateA-month" -> One("1"),
        "1_dateA-year"  -> One("2000"),
        "1_dateB-day"   -> One("2"),
        "1_dateB-month" -> One("2"),
        "1_dateB-year"  -> One("2024"),
        "2_addAnotherB" -> Many(List("0")),
        "2_amountB"     -> One("3"),
        "2_controlB"    -> Many(List("offset")),
        "2_dateB-day"   -> One("3"),
        "2_dateB-month" -> One("3"),
        "2_dateB-year"  -> One("2023"),
        "3_addAnotherB" -> Many(List("1")),
        "3_amountB"     -> One("4"),
        "3_controlB"    -> Many(List("keep"))
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ap1.2.1",
        "ar1.2",
        "ap1.3.0",
        "ar1.3"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amountA"     -> NumberResult(1),
        "1_amountB"     -> NumberResult(2),
        "1_controlA"    -> OptionResult(List("offset")),
        "1_controlB"    -> OptionResult(List("offset")),
        "1_dateA-day"   -> NumberResult(1),
        "1_dateA-month" -> NumberResult(1),
        "1_dateA-year"  -> NumberResult(2000),
        "1_dateB-day"   -> NumberResult(2),
        "1_dateB-month" -> NumberResult(2),
        "1_dateB-year"  -> NumberResult(2024),
        "2_amountB"     -> NumberResult(3),
        "2_controlB"    -> OptionResult(List("offset")),
        "2_dateB-day"   -> NumberResult(3),
        "2_dateB-month" -> NumberResult(3),
        "2_dateB-year"  -> NumberResult(2023),
        "3_amountB"     -> NumberResult(4),
        "3_controlB"    -> OptionResult(List("keep")),
        "3_dateB-day"   -> Hidden,
        "3_dateB-month" -> Hidden,
        "3_dateB-year"  -> Hidden,
        "secret"        -> Empty
      ),
      List(
        "1 - data: 1 : 1 January 2000",
        "<p>1 - data: 1 : 1 January 2000</p>",
        "1 - data: 2 : 2 February 2024",
        "<p>1 - data: 2 : 2 February 2024</p>",
        "2 - data: 3 : 3 March 2023",
        "<p>2 - data: 3 : 3 March 2023</p>",
        "3 - data: 4 : ",
        "<p>3 - data: 4 :</p>",
        "calculation.sum = 70",
        "calculation = 23, 23, 24",
        "amountA: 1",
        "amountB: 2, 3, 4",
        "dateA: 1 January 2000",
        "dateB: 2 February 2024, 3 March 2023",
        "dateA after 31122024: No",
        "dateB before 01012024: No, Yes, No",
        "dateA after 31122024 && dateB before 01012024: No, No, No",
        "offset: 20, 20, 20"
      ),
      "sum-with-and-and-two-atls.json No x No"
    ),
    (
      MongoUserData(
        "1_addAnotherA" -> Many(List("1")),
        "1_addAnotherB" -> Many(List("0")),
        "1_amountA"     -> One("1"),
        "1_amountB"     -> One("2"),
        "1_controlA"    -> Many(List("offset")),
        "1_controlB"    -> Many(List("offset")),
        "1_dateA-day"   -> One("1"),
        "1_dateA-month" -> One("1"),
        "1_dateA-year"  -> One("2025"),
        "1_dateB-day"   -> One("2"),
        "1_dateB-month" -> One("2"),
        "1_dateB-year"  -> One("2023"),
        "2_addAnotherB" -> Many(List("0")),
        "2_amountB"     -> One("3"),
        "2_controlB"    -> Many(List("offset")),
        "2_dateB-day"   -> One("3"),
        "2_dateB-month" -> One("3"),
        "2_dateB-year"  -> One("2023"),
        "3_addAnotherB" -> Many(List("1")),
        "3_amountB"     -> One("4"),
        "3_controlB"    -> Many(List("keep"))
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap1.1.0",
        "ap1.1.1",
        "ar1.1",
        "ap1.2.0",
        "ap1.2.1",
        "ar1.2",
        "ap1.3.0",
        "ar1.3"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amountA"     -> NumberResult(1),
        "1_amountB"     -> NumberResult(2),
        "1_controlA"    -> OptionResult(List("offset")),
        "1_controlB"    -> OptionResult(List("offset")),
        "1_dateA-day"   -> NumberResult(1),
        "1_dateA-month" -> NumberResult(1),
        "1_dateA-year"  -> NumberResult(2025),
        "1_dateB-day"   -> NumberResult(2),
        "1_dateB-month" -> NumberResult(2),
        "1_dateB-year"  -> NumberResult(2023),
        "2_amountB"     -> NumberResult(3),
        "2_controlB"    -> OptionResult(List("offset")),
        "2_dateB-day"   -> NumberResult(3),
        "2_dateB-month" -> NumberResult(3),
        "2_dateB-year"  -> NumberResult(2023),
        "3_amountB"     -> NumberResult(4),
        "3_controlB"    -> OptionResult(List("keep")),
        "3_dateB-day"   -> Hidden,
        "3_dateB-month" -> Hidden,
        "3_dateB-year"  -> Hidden,
        "secret"        -> Hidden
      ),
      List(
        "1 - data: 1 : 1 January 2025",
        "<p>1 - data: 1 : 1 January 2025</p>",
        "1 - data: 2 : 2 February 2023",
        "<p>1 - data: 2 : 2 February 2023</p>",
        "2 - data: 3 : 3 March 2023",
        "<p>2 - data: 3 : 3 March 2023</p>",
        "3 - data: 4 : ",
        "<p>3 - data: 4 :</p>",
        "calculation.sum = 60",
        "calculation = 13, 23, 24",
        "amountA: 1",
        "amountB: 2, 3, 4",
        "dateA: 1 January 2025",
        "dateB: 2 February 2023, 3 March 2023",
        "dateA after 31122024: Yes",
        "dateB before 01012024: Yes, Yes, No",
        "dateA after 31122024 && dateB before 01012024: Yes, No, No",
        "offset: 10, 20, 20"
      ),
      "sum-with-and-and-two-atls.json Yes x Yes"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("keep")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_date-day"   -> One("1"),
        "2_date-month" -> One("1"),
        "2_date-year"  -> One("2020"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("offset")),
        "3_date-day"   -> One("1"),
        "3_date-month" -> One("1"),
        "3_date-year"  -> One("2025"),
        "dummy"        -> One("dummy"),
        "secret"       -> Many(List("found"))
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"     -> NumberResult(1),
        "1_control"    -> OptionResult(List("keep")),
        "1_date-day"   -> Hidden,
        "1_date-month" -> Hidden,
        "1_date-year"  -> Hidden,
        "2_amount"     -> NumberResult(2),
        "2_control"    -> OptionResult(List("offset")),
        "2_date-day"   -> NumberResult(1),
        "2_date-month" -> NumberResult(1),
        "2_date-year"  -> NumberResult(2020),
        "3_amount"     -> NumberResult(3),
        "3_control"    -> OptionResult(List("offset")),
        "3_date-day"   -> NumberResult(1),
        "3_date-month" -> NumberResult(1),
        "3_date-year"  -> NumberResult(2025),
        "secret"       -> OptionResult(List("found"))
      ),
      List(
        "1 - data: 1 :  : 20 : 21 : 21",
        "<p>1 - data: 1 : : 20 : 21 : 21</p>",
        "2 - data: 2 : 1 January 2020 : 10 : 12 : 33",
        "<p>2 - data: 2 : 1 January 2020 : 10 : 12 : 33</p>",
        "3 - data: 3 : 1 January 2025 : 20 : 23 : 56",
        "<p>3 - data: 3 : 1 January 2025 : 20 : 23 : 56</p>",
        "calculation.sum = 56",
        "calculation = 21, 12, 23",
        "amount: 1, 2, 3",
        "offset: 20, 10, 20",
        "date: 1 January 2020, 1 January 2025",
        "secret: Found"
      ),
      "sum-with-date-before.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("keep")),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_date-day"   -> One("1"),
        "2_date-month" -> One("1"),
        "2_date-year"  -> One("2020"),
        "3_addAnother" -> Many(List("1")),
        "3_amount"     -> One("4"),
        "3_control"    -> Many(List("offset")),
        "3_date-day"   -> One("1"),
        "3_date-month" -> One("1"),
        "3_date-year"  -> One("2025"),
        "dummy"        -> One("dummy"),
        "secret"       -> Many(List("found"))
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"     -> NumberResult(1),
        "1_control"    -> OptionResult(List("keep")),
        "1_date-day"   -> Hidden,
        "1_date-month" -> Hidden,
        "1_date-year"  -> Hidden,
        "2_amount"     -> NumberResult(2),
        "2_control"    -> OptionResult(List("offset")),
        "2_date-day"   -> NumberResult(1),
        "2_date-month" -> NumberResult(1),
        "2_date-year"  -> NumberResult(2020),
        "3_amount"     -> NumberResult(4),
        "3_control"    -> OptionResult(List("offset")),
        "3_date-day"   -> NumberResult(1),
        "3_date-month" -> NumberResult(1),
        "3_date-year"  -> NumberResult(2025),
        "secret"       -> Hidden
      ),
      List(
        "1 - data: 1 :  : 20 : 21 : 21",
        "<p>1 - data: 1 : : 20 : 21 : 21</p>",
        "2 - data: 2 : 1 January 2020 : 10 : 12 : 33",
        "<p>2 - data: 2 : 1 January 2020 : 10 : 12 : 33</p>",
        "3 - data: 4 : 1 January 2025 : 20 : 24 : 57",
        "<p>3 - data: 4 : 1 January 2025 : 20 : 24 : 57</p>",
        "calculation.sum = 57",
        "calculation = 21, 12, 24",
        "amount: 1, 2, 4",
        "offset: 20, 10, 20",
        "date: 1 January 2020, 1 January 2025",
        "secret: "
      ),
      "sum-with-date-before.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_date-day"   -> One("5"),
        "1_date-month" -> One("6"),
        "1_date-year"  -> One("2024"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_date-day"   -> One("1"),
        "2_date-month" -> One("1"),
        "2_date-year"  -> One("2023"),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("offset")),
        "3_date-day"   -> One("1"),
        "3_date-month" -> One("1"),
        "3_date-year"  -> One("2025"),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("4"),
        "4_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"     -> NumberResult(1),
        "1_control"    -> OptionResult(List("offset")),
        "1_date-day"   -> NumberResult(5),
        "1_date-month" -> NumberResult(6),
        "1_date-year"  -> NumberResult(2024),
        "2_amount"     -> NumberResult(2),
        "2_control"    -> OptionResult(List("offset")),
        "2_date-day"   -> NumberResult(1),
        "2_date-month" -> NumberResult(1),
        "2_date-year"  -> NumberResult(2023),
        "3_amount"     -> NumberResult(3),
        "3_control"    -> OptionResult(List("offset")),
        "3_date-day"   -> NumberResult(1),
        "3_date-month" -> NumberResult(1),
        "3_date-year"  -> NumberResult(2025),
        "4_amount"     -> NumberResult(4),
        "4_control"    -> OptionResult(List("keep")),
        "4_date-day"   -> Hidden,
        "4_date-month" -> Hidden,
        "4_date-year"  -> Hidden,
        "secret"       -> Empty
      ),
      List(
        "1 - data: 1 : 5 June 2024 : 20 : 21 : 21",
        "<p>1 - data: 1 : 5 June 2024 : 20 : 21 : 21</p>",
        "2 - data: 2 : 1 January 2023 : 20 : 22 : 43",
        "<p>2 - data: 2 : 1 January 2023 : 20 : 22 : 43</p>",
        "3 - data: 3 : 1 January 2025 : 20 : 23 : 66",
        "<p>3 - data: 3 : 1 January 2025 : 20 : 23 : 66</p>",
        "4 - data: 4 :  : 20 : 24 : 90",
        "<p>4 - data: 4 : : 20 : 24 : 90</p>",
        "calculation.sum = 90",
        "calculation = 21, 22, 23, 24",
        "amount: 1, 2, 3, 4",
        "offset: 20, 20, 20, 20",
        "date: 5 June 2024, 1 January 2023, 1 January 2025"
      ),
      "sum-with-and.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother" -> Many(List("0")),
        "1_amount"     -> One("1"),
        "1_control"    -> Many(List("offset")),
        "1_date-day"   -> One("5"),
        "1_date-month" -> One("6"),
        "1_date-year"  -> One("2024"),
        "2_addAnother" -> Many(List("0")),
        "2_amount"     -> One("2"),
        "2_control"    -> Many(List("offset")),
        "2_date-day"   -> One("1"),
        "2_date-month" -> One("1"),
        "2_date-year"  -> One("2023"),
        "3_addAnother" -> Many(List("0")),
        "3_amount"     -> One("3"),
        "3_control"    -> Many(List("offset")),
        "3_date-day"   -> One("1"),
        "3_date-month" -> One("1"),
        "3_date-year"  -> One("2025"),
        "4_addAnother" -> Many(List("1")),
        "4_amount"     -> One("5"),
        "4_control"    -> Many(List("keep")),
        "dummy"        -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ap0.1.1",
        "ar0.1",
        "ap0.2.0",
        "ap0.2.1",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "ap0.4.0",
        "ar0.4",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_amount"     -> NumberResult(1),
        "1_control"    -> OptionResult(List("offset")),
        "1_date-day"   -> NumberResult(5),
        "1_date-month" -> NumberResult(6),
        "1_date-year"  -> NumberResult(2024),
        "2_amount"     -> NumberResult(2),
        "2_control"    -> OptionResult(List("offset")),
        "2_date-day"   -> NumberResult(1),
        "2_date-month" -> NumberResult(1),
        "2_date-year"  -> NumberResult(2023),
        "3_amount"     -> NumberResult(3),
        "3_control"    -> OptionResult(List("offset")),
        "3_date-day"   -> NumberResult(1),
        "3_date-month" -> NumberResult(1),
        "3_date-year"  -> NumberResult(2025),
        "4_amount"     -> NumberResult(5),
        "4_control"    -> OptionResult(List("keep")),
        "4_date-day"   -> Hidden,
        "4_date-month" -> Hidden,
        "4_date-year"  -> Hidden,
        "secret"       -> Hidden
      ),
      List(
        "1 - data: 1 : 5 June 2024 : 20 : 21 : 21",
        "<p>1 - data: 1 : 5 June 2024 : 20 : 21 : 21</p>",
        "2 - data: 2 : 1 January 2023 : 20 : 22 : 43",
        "<p>2 - data: 2 : 1 January 2023 : 20 : 22 : 43</p>",
        "3 - data: 3 : 1 January 2025 : 20 : 23 : 66",
        "<p>3 - data: 3 : 1 January 2025 : 20 : 23 : 66</p>",
        "4 - data: 5 :  : 20 : 25 : 91",
        "<p>4 - data: 5 : : 20 : 25 : 91</p>",
        "calculation.sum = 91",
        "calculation = 21, 22, 23, 25",
        "amount: 1, 2, 3, 5",
        "offset: 20, 20, 20, 20",
        "date: 5 June 2024, 1 January 2023, 1 January 2025"
      ),
      "sum-with-and.json secret not found"
    ),
    (
      MongoUserData(
        "1_addAnother"      -> Many(List("0")),
        "1_pageA"           -> One("1"),
        "2_addAnother"      -> Many(List("0")),
        "2_pageA"           -> One("2"),
        "3_addAnother"      -> Many(List("1")),
        "3_pageA"           -> One("100"),
        "3_startDate-day"   -> One("1"),
        "3_startDate-month" -> One("1"),
        "3_startDate-year"  -> One("2025"),
        "dummy"             -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_pageA"           -> NumberResult(1),
        "1_startDate-day"   -> Hidden,
        "1_startDate-month" -> Hidden,
        "1_startDate-year"  -> Hidden,
        "2_pageA"           -> NumberResult(2),
        "2_startDate-day"   -> Hidden,
        "2_startDate-month" -> Hidden,
        "2_startDate-year"  -> Hidden,
        "3_pageA"           -> NumberResult(100),
        "3_startDate-day"   -> NumberResult(1),
        "3_startDate-month" -> NumberResult(1),
        "3_startDate-year"  -> NumberResult(2025),
        "secret"            -> Empty
      ),
      List(
        "Sum test: 21",
        "external expression sum: 21",
        "Data: 1:  : 20 : 21 : 21",
        "<p>Data: 1: : 20 : 21 : 21</p>",
        "Sum test: 43",
        "external expression sum: 43",
        "Data: 2:  : 20 : 22 : 43",
        "<p>Data: 2: : 20 : 22 : 43</p>",
        "Sum test: 153",
        "external expression sum: 153",
        "Data: 100: 1 January 2025 : 10 : 110 : 153",
        "<p>Data: 100: 1 January 2025 : 10 : 110 : 153</p>",
        "calculation.sum = 153",
        "calculation = 21, 22, 110",
        "pageA: 1, 2, 100"
      ),
      "sum-with-date-after.json secret found"
    ),
    (
      MongoUserData(
        "1_addAnother"      -> Many(List("0")),
        "1_pageA"           -> One("1"),
        "2_addAnother"      -> Many(List("0")),
        "2_pageA"           -> One("2"),
        "3_addAnother"      -> Many(List("1")),
        "3_pageA"           -> One("101"),
        "3_startDate-day"   -> One("1"),
        "3_startDate-month" -> One("1"),
        "3_startDate-year"  -> One("2025"),
        "dummy"             -> One("dummy")
      ),
      List(
        "ap0.1.0",
        "ar0.1",
        "ap0.2.0",
        "ar0.2",
        "ap0.3.0",
        "ap0.3.1",
        "ar0.3",
        "n1"
      ),
      EvaluationContext.empty,
      AnswerMap(
        "1_pageA"           -> NumberResult(1),
        "1_startDate-day"   -> Hidden,
        "1_startDate-month" -> Hidden,
        "1_startDate-year"  -> Hidden,
        "2_pageA"           -> NumberResult(2),
        "2_startDate-day"   -> Hidden,
        "2_startDate-month" -> Hidden,
        "2_startDate-year"  -> Hidden,
        "3_pageA"           -> NumberResult(101),
        "3_startDate-day"   -> NumberResult(1),
        "3_startDate-month" -> NumberResult(1),
        "3_startDate-year"  -> NumberResult(2025),
        "secret"            -> Hidden
      ),
      List(
        "Sum test: 21",
        "external expression sum: 21",
        "Data: 1:  : 20 : 21 : 21",
        "<p>Data: 1: : 20 : 21 : 21</p>",
        "Sum test: 43",
        "external expression sum: 43",
        "Data: 2:  : 20 : 22 : 43",
        "<p>Data: 2: : 20 : 22 : 43</p>",
        "Sum test: 154",
        "external expression sum: 154",
        "Data: 101: 1 January 2025 : 10 : 111 : 154",
        "<p>Data: 101: 1 January 2025 : 10 : 111 : 154</p>",
        "calculation.sum = 154",
        "calculation = 21, 22, 111",
        "pageA: 1, 2, 101"
      ),
      "sum-with-date-after.json secret not found"
    )
  )
}
